name: PipelineWorkflow

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Azure Pipeline
        runs-on: windows-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/manitlearndevops1998/test3
            azure-pipeline-name: 'test3'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}